# Generated by Django 2.1.4 on 2018-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181221_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerurls',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
