# Generated by Django 2.1.4 on 2018-12-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181224_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerurls',
            name='internalStatus',
            field=models.BooleanField(default=False),
        ),
    ]
