# Generated by Django 2.1.4 on 2018-12-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_crawlerurls_internalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedurls',
            name='relatedUrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ScrapedUrls', verbose_name='Related Url'),
        ),
    ]
